### ISSUE TITLE
Fails to mark threads as read.

### ISSUE THREAD

**Issue by Neppkun** [FedeIlLeone/ReadAllButton#1]
Plugin fails to mark any threads with messages as read.

https://user-images.githubusercontent.com/57060018/222446922-3f5a3ed9-16d6-4677-a1a7-c6ddf8a09033.mp4

Replugged v4.0.0-rc.2
ReadAllButton 1.0.0

**Comment by fedeericodl** [comment]
Threads and DMs are not touched by the plugin **yet**. I'll make sure to add support for these ASAP.

**Comment by Neppkun** [comment]
> Threads and DMs are not touched by the plugin **yet**. I'll make sure to add support for these ASAP.

Great. It'd be nice to have options to toggle what the plugin should mark as read too.

**Comment by fedeericodl** [comment]
Added threads support in v1.1.0. I added the options thing to the to-do list as well. Thanks!
